### ISSUE TITLE
Test Meetings Calendar Exclusions

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#942]
We created new meeting bodies below:
Name: Test - Live Regular Meeting Test
Body GUID: E9D67551-2D97-4423-B385-93EF722587B3
BodyId: 300

Name: Test - Live Regular Meeting Test (SAP)
Body GUID: 9E0FD2EF-A9FD-4401-A68F-A25534B60AEC
BodyId: 302

Name: Test - Live Committee Meeting Test
Body GUID: 63298F67-445C-459C-8294-EE1FBD0FE5A1
BodyId: 301

Name: Test - Live Committee Meeting Test (SAP)
Body GUID: 438A361C-DCB4-4BD6-9E58-00DF203890D4
BodyId: 303

Are we able to exclude these from being shown on the boardagendas site meeting calendar? We would still like them to show up on the live meeting section so that we can test broadcast links.

**Comment by hancush** [comment]
Next meetings week of 3/13.

**Comment by xmedr** [comment]
We'll be updating the scraper to bring in test events, and updating the app to exclude them from the events view.

**Comment by xmedr** [comment]
@shrayshray We've almost gotten to a solution on this, and we'll be able to finish up on Monday 3/10

**Comment by hancush** [comment]
@shrayshray @neilarellano We published a patch for this, this week. You should no longer see test events on the event listing page. Please let us know if any sneak through!

**Comment by neilarellano** [comment]
Hi @hancush,

I created a test meeting for this week and it seems like it is still showing up for the upcoming meetings section on the front page. Please see screenshot:

![image](https://user-images.githubusercontent.com/110051034/226330168-421a944b-4b91-487e-b515-d58440cb9180.png)

It doesn't seem to appear on https://boardagendas.metro.net/events/

**Comment by hancush** [comment]
Ah, thanks for letting us know, @neilarellano! 

@xmedr Can you take a look at this today? Should be able to exclude them from the homepage similarly to how you excluded them from the event listing page.

**Comment by neilarellano** [comment]
Hi @hancush ,

I just created another test meeting and it seems like it still is showing up. Please see screenshot:

![image](https://user-images.githubusercontent.com/110051034/226479261-59e2bc54-de23-46d2-b672-eff0f6fffcef.png)

**Comment by hancush** [comment]
@neilarellano Needed to deploy the change. Just published, test events should no longer appear.
